version: 2.1

jobs:
  build:
    parameters:
      xcode_version:
        type: string
    macos:
      xcode: << parameters.xcode_version >>
    steps:
      - checkout
      - run: make

workflows:
  test:
    jobs:
      - build:
          matrix:
            parameters:
              xcode_version: [14.3.0, 14.2.0, 14.1.0]
