version: 2.1

jobs:
  build:
    parameters:
      xcode_version:
        type: string
    macos:
      xcode: << parameters.xcode_version >>
    steps:
      - checkout
      - run: make

workflows:
  test:
    jobs:
      - build:
          matrix:
            parameters:
              xcode_version: [
                14.3.0,   # macOS 13.2
                14.2.0,   # macOS 12.6
                14.1.0,   # macOS 12.5.1
                13.4.1,   # macOS 12.3.1
                13.2.1,   # macOS 11.6.2
                13.0.0,   # macOS 11.5.2
                12.5.1,   # macOS 11.4.0
                11.7.0    # macOS 10.15.5
                ]
