version: 2.1

jobs:
  build:
    macos:
      xcode: << parameters.xcode-version >>
    parameters:
      xcode_version:
        type: string
    steps:
      - checkout
      - run: make

workflows:
  test:
    jobs:
      - build
          matrix:
            parameters:
              xcode-version: [14.3.0, 14.2.0, 14.1.0]
