version: 2.1

jobs:
  build-macos:
    parameters:
      xcode_version:
        type: string
    macos:
      xcode: << parameters.xcode_version >>
    steps:
      - checkout
      - run:
          name: Makefile
          command: make
      - run:
          name: Test executable
          command: ./qpress -v readme.md readme.qp

  build-linux:
    parameters:
      image:
        type: string
    machine:
      image: << parameters.image >>
    steps:
      - checkout
      - run:
          name: Makefile
          command: make
      - run:
          name: Test executable
          command: ./qpress -v readme.md readme.qp

workflows:
  test-macos:
    jobs:
      - build-macos:
          matrix:
            parameters:
              xcode_version: [
                15.4.0,   # macOS 14+
                14.3.1,   # macOS 13+
                13.4.1,   # macOS 12+
                ]
  test-linux:
    jobs:
      - build-linux:
          matrix:
            parameters:
              image: [ubuntu-2404:current, ubuntu-2204:current, ubuntu-2004:current]
